"""adiciona status de participacao aos participantes

Revision ID: 352f5cbe9267
Revises: 89c693975f72
Create Date: 2026-08-13 15:15:03.402216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352f5cbe9267'
down_revision: Union[str, Sequence[str], None] = '89c693975f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'racha_participants',
        sa.Column(
            'participation_status',
            sa.String(length=20),
            nullable=False,
            server_default='Confirmado',
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('racha_participants', 'participation_status')
    # ### end Alembic commands ###
