"""adiciona status de pagamento aos participantes

Revision ID: 89c693975f72
Revises: 10c825d7635d
Create Date: 2026-08-12 17:44:24.186250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c693975f72'
down_revision: Union[str, Sequence[str], None] = '10c825d7635d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'racha_participants',
        sa.Column(
            'payment_status',
            sa.String(length=20),
            nullable=False,
            server_default='Pendente',
        ),
    )
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('racha_participants', 'payment_status')
    # ### end Alembic commands ###
