"""adiciona preferencia de participacao ao usuario

Revision ID: 9014cebfc68a
Revises: 352f5cbe9267
Create Date: 2026-08-18 10:52:42.828780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9014cebfc68a'
down_revision: Union[str, Sequence[str], None] = '352f5cbe9267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_role', sa.String(length=20), server_default='Jogador', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_role')
    # ### end Alembic commands ###
